create table student
(
    id        integer generated by default as identity
        primary key,
    name      varchar(100) not null,
    birthdate date         not null,
    phone     bigint       not null,
    school_id integer      not null
        constraint student_school_id_fk
            references school
);

alter table student
    owner to postgres;

